"""
Write a program that has three threads in it. The first thread should produce a random numbers in the range 1 to 20.
the second thread should display the square of the number generated by first thread on the screen, and the third should
write cube of number generated by the first number into a file.
"""

import threading
import random
import time
import collections

def generate():
    for i in range(5):
        cond.acquire()
        num = random.randrange(1, 20)
        print("Generated number:- ", num)
        qfors.append(num)
        qforc.append(num)
        cond.notify_all()
        cond.release()


def square():
    for i in range(0, 5):
        cond.acquire()
        if len(qfors):
            num = qfors.popleft()
            print('Num:-', num, 'Square:- ', num * num)
        cond.notify_all()
        cond.release()

def cube():
    for i in range(0, 5):
        cond.acquire()

        if len(qforc):
            num = qforc.popleft()
            f.write(f'Num:- {str(num)} Cube:-  {str(num * num * num)} \n')
            cond.notify_all()
        cond.release()


f = open('cubes.txt', 'w')
qfors = collections.deque()
qforc = collections.deque()
cond = threading.Condition()
th1 = threading.Thread(target=generate)
th2 = threading.Thread(target=square)
th3 = threading.Thread(target=cube)
th1.start()
th2.start()
th3.start()
th1.join()
th2.join()
th3.join()
print('All Done!!')


